[package]
name = "fortis"
version = "0.1.0"
edition = "2021"

[dependencies]
deepgram = "0.7"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
cpal = "0.13"
dotenv = "0.15.0"
chrono = "0.4"
hound = "3.5"
async-trait = "0.1"
ratatui = "0.27"
crossterm = "0.28"
